name: Trigger auto deployment for cancer-prediction

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cancer-prediction-AutoDeployTrigger-d2c69ea4-b1e1-46ac-8267-134551d0624e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CANCERPREDICTION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CANCERPREDICTION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CANCERPREDICTION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.CANCERPREDICTION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CANCERPREDICTION_REGISTRY_PASSWORD }}
          containerAppName: cancer-prediction
          resourceGroup: fastapi
          imageToBuild: saneeparth99/cancer-prediction:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


